# Site settings
name: Company Carpool
title: "Carpooling service for companies and organizations | Company Carpool"
email: info@companycarpool.com
description: "Carpooling service for companies and organizations"
baseurl: ""
url: "http://www.companycarpool.com"

# Custom settings
google_analytics_tracking_code: UA-42088973-2

languages:
  en: English
  it: Italiano
  es: Español
  fr: Français
  pt: Português
  ru: Русский

localized_pages:
  root:
    -
      language: en
      url: '/'
    -
      language: it
      url: '/it/'
    -
      language: es
      url: '/es/'
    -
      language: fr
      url: '/fr/'
    -
      language: pt
      url: '/pt/'
    -
      language: ru
      url: '/ru/'

navbar_links:
  en:
    how-it-works: How It Works
    demo: Demo
    free-trial: Free Trial
    toggle-navigation: Toggle navigation
  it:
    how-it-works: Come Funziona
    demo: Demo
    free-trial: Prova gratuita
    toggle-navigation: Menù di navigazione
  es:
    how-it-works: Cómo funciona
    demo: Demo
    free-trial: Prueba gratuita
    toggle-navigation: Menú de navegación
  fr:
    how-it-works: Mode de fonctionnement
    demo: Demo
    free-trial: Essai gratuit
    toggle-navigation: Menu de navigation
  pt:
    how-it-works: Como funciona
    demo: Demo
    free-trial: Teste grátis
    toggle-navigation: Menu de navegação
  ru:
    how-it-works: Как это работает
    demo: Demo
    free-trial: Бесплатная пробная
    toggle-navigation: Меню навигации

# Build settings
markdown: kramdown
permalinks: pretty

# Plugins
plugins:
  - jekyll-assets
  - jekyll-minify-html
  - jekyll-sitemap

#
# Plugin: jekyll-assets
#
assets:
  compress:
    css: true
    js: true
  destination: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors/javascripts
    - _vendors/stylesheets
